apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk-dev
  labels:
    app: kibana
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.name: "kibana"
    elasticsearch.hosts: ["http://es01:9200", "http://es02:9200", "http://es03:9200" ]